### ISSUE TITLE
[BUG] Minimum prices are not working

### ISSUE THREAD

**Issue by quiquelhappy** [Ghost-chu/QuickShop-Hikari#1684]
### Description

price restrictions are not working at all

### Steps to reproduce

1. set ```enable`` to true on price-restrictions.yml
2. restart the server
3. try to create a shop with a restricted price
4. the shop creation does not get prevented when the price is below min or above max

### Expected Behaviour

price restrictions should prevent creation of shops that are outside the permitted scope

### `/quickshop paste` URL

https://paste.helpch.at/jabiguzogu.bash

### Additional Context

I'm using the build matching 6.2.0.6, but this happens on the published version on modrinth and spigot too.

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by YuanYuanOwO** [comment]
![QQ_1721477383027](https://github.com/user-attachments/assets/c5ede03e-8ae5-4e9a-995e-d99581b90f32)
maybe you need to change `price-restriction.yml`

**Comment by quiquelhappy** [comment]
I'll try to regenerate the file. Is there something I need to enable on the separate config.yml? Or enabling it on the restriction file is enough? PS: I was using the default config and changed enable to true to test this

**Comment by YuanYuanOwO** [comment]
> I'll try to regenerate the file. Is there something I need to enable on the separate config.yml? Or enabling it on the restriction file is enough? PS: I was using the default config and changed enable to true to test this

> enabling it on the restriction file is enough?  

 yes,only enable it on restriction file.

> I was using the default config and changed enable to true to test this.  

if you are using default file,try create a free shop(0 price) to test it.
I don't think the default file actually makes any restrictions
You may to change `undefined-min` and `undefined-max`

**Comment by quiquelhappy** [comment]
I believe there are defaults, I would appreciate it if you could send an example restrictions file to make sure that what I'm using makes sense :). Sorry and thanks for your time.

**Comment by YuanYuanOwO** [comment]
> I believe there are defaults, I would appreciate it if you could send an example restrictions file to make sure that what I'm using makes sense :). Sorry and thanks for your time.

There is currently no time to change the file to make it simpler and easier to understand

**Comment by creatorfromhell** [comment]
> I believe there are defaults, I would appreciate it if you could send an example restrictions file to make sure that what I'm using makes sense :). Sorry and thanks for your time.

Post what you've tried versus asking for an example file. I.e. your restrictions file that you tried to config as insinuated in the initial report.

**Comment by quiquelhappy** [comment]
The one I was trying to test originally
```yml
version: 3
whole-number-only: false  # This option not control by enable option, always enabled
undefined: # This option not control by enable option, always enabled
  min: 1 # Can be zero if you want player create a free shop
  max: 1000000 # Actually this can be up to 1.7976931348623157E308
enable: true
rules:
  elytra:
    items:
      - ELYTRA
    currency:
      - '*'
    min: 2500.0
    max: 1000000.0
  ancient_debris:
    items:
      - ANCIENT_DEBRIS
    currency:
      - '*'
    min: 300.0
    max: 1000000.0
  netherite_block:
    items:
      - NETHERITE_BLOCK
    currency:
      - '*'
    min: 14500.0
    max: 1000000.0
  shulker_shell:
    items:
      - NETHERITE_BLOCK
    currency:
      - '*'
    min: 165.0
    max: 1000000.0
  shulker_box:
    items:
    - BLUE_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - CYAN_SHULKER_BOX
    - GRAY_SHULKER_BOX
    - GREEN_SHULKER_BOX
    - LIGHT_BLUE_SHULKER_BOX
    - LIGHT_GRAY_SHULKER_BOX
    - LIME_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - PINK_SHULKER_BOX
    - PURPLE_SHULKER_BOX
    - RED_SHULKER_BOX
    - WHITE_SHULKER_BOX
    - YELLOW_SHULKER_BOX
    - BLACK_SHULKER_BOX
    - SHULKER_BOX
    currency:
      - '*'
    min: 330.0
    max: 1000000.0
  enchanted_book:
    items:
      - ENCHANTED_BOOK
    currency:
      - '*'
    min: 75.0
    max: 1000000.0
  diamond:
    items:
      - DIAMOND
    currency:
      - '*'
    min: 75.0
    max: 1000000.0
  beacon:
    items:
      - BEACON
    currency:
      - '*'
    min: 1250.0
    max: 1000000.0
  netherite_stuff:
    items:
      - NETHERITE_INGOT
      - NETHERITE_HOE
      - NETHERITE_SWORD
      - NETHERITE_PICKAXE
      - NETHERITE_SHOVEL
      - NETHERITE_AXE
      - NETHERITE_BOOTS
      - NETHERITE_CHESTPLATE
      - NETHERITE_HELMET
      - NETHERITE_LEGGINGS
    currency:
      - '*'
    min: 1000.0
    max: 1000000.0
  diamond_stuff:
    items:
      - DIAMOND_AXE
      - DIAMOND_SWORD
      - DIAMOND_HOE
      - DIAMOND_PICKAXE
      - DIAMOND_SHOVEL
      - DIAMOND_SWORD
      - ENCHANTED_GOLDEN_APPLE
    currency:
      - '*'
    min: 100.0
    max: 1000000.0
  trims:
    items:
    - BOLT_ARMOR_TRIM_SMITHING_TEMPLATE
    - COAST_ARMOR_TRIM_SMITHING_TEMPLATE
    - DUNE_ARMOR_TRIM_SMITHING_TEMPLATE
    - EYE_ARMOR_TRIM_SMITHING_TEMPLATE
    - FLOW_ARMOR_TRIM_SMITHING_TEMPLATE
    - HOST_ARMOR_TRIM_SMITHING_TEMPLATE
    - RAISER_ARMOR_TRIM_SMITHING_TEMPLATE
    - RIB_ARMOR_TRIM_SMITHING_TEMPLATE
    - SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE
    - SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE
    - SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE
    - SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE
    - SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE
    - TIDE_ARMOR_TRIM_SMITHING_TEMPLATE
    - VEX_ARMOR_TRIM_SMITHING_TEMPLATE
    - WARD_ARMOR_TRIM_SMITHING_TEMPLATE
    - WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE
    - WILD_ARMOR_TRIM_SMITHING_TEMPLATE
    currency:
      - '*'
    min: 175.0
    max: 1000000.0
  basics:
    items:
    - STONE
    - DIORITE
    - ANDESITE
    - GRANITE
    currency:
      - '*'
    min: 2.0
    max: 1000000.0
  iron_block:
    items:
      - IRON_BLOCK
    currency:
      - '*'
    min: 9.0
    max: 1000000.0

  emerald_block:
    items:
      - EMERALD_BLOCK
    currency:
      - '*'
    min: 9.0
    max: 1000000.0

  gold_ingot:
    items:
      - GOLD_INGOT
    currency:
      - '*'
    min: 3.0
    max: 1000000.0

  gold_block:
    items:
      - GOLD_BLOCK
    currency:
      - '*'
    min: 27.0
    max: 1000000.0

  lapis_block:
    items:
      - LAPIS_BLOCK
    currency:
      - '*'
    min: 6.0
    max: 1000000.0

  coal_block:
    items:
      - COAL_BLOCK
    currency:
      - '*'
    min: 6.0
    max: 1000000.0

  wither_skeleton_skull:
    items:
      - WITHER_SKELETON_SKULL
    currency:
      - '*'
    min: 375.0
    max: 1000000.0

  deepslate_diamond_ore:
    items:
      - DEEPSLATE_DIAMOND_ORE
    currency:
      - '*'
    min: 30.0
    max: 1000000.0

  diamond_ore:
    items:
      - DIAMOND_ORE
    currency:
      - '*'
    min: 30.0
    max: 1000000.0

  trident:
    items:
      - TRIDENT
    currency:
      - '*'
    min: 500.0
    max: 1000000.0

  totem_of_undying:
    items:
      - TOTEM_OF_UNDYING
    currency:
      - '*'
    min: 20.0
    max: 1000000.0

  diamond_block:
    items:
      - DIAMOND_BLOCK
    currency:
      - '*'
    min: 180.0
    max: 1000000.0

  redstone_block:
    items:
      - REDSTONE_BLOCK
    currency:
      - '*'
    min: 7.0
    max: 1000000.0

  spawner:
    items:
      - SPAWNER
    currency:
      - '*'
    min: 750.0
    max: 1000000.0

  tnt:
    items:
      - TNT
    currency:
      - '*'
    min: 15.0
    max: 1000000.0

  golden_apple:
    items:
      - GOLDEN_APPLE
    currency:
      - '*'
    min: 10.0
    max: 1000000.0

  lead:
    items:
      - LEAD
    currency:
      - '*'
    min: 2.0
    max: 1000000.0

  bee_nest:
    items:
      - BEE_NEST
    currency:
      - '*'
    min: 15.0
    max: 1000000.0

  netherite_upgrade_smithing_template:
    items:
      - NETHERITE_UPGRADE_SMITHING_TEMPLATE
    currency:
      - '*'
    min: 350.0
    max: 1000000.0

  golden_carrot:
    items:
      - GOLDEN_CARROT
    currency:
      - '*'
    min: 3.0
    max: 1000000.0

  wither_rose:
    items:
      - WITHER_ROSE
    currency:
      - '*'
    min: 7.0
    max: 1000000.0

  potted_wither_rose:
    items:
      - POTTED_WITHER_ROSE
    currency:
      - '*'
    min: 7.0
    max: 1000000.0

  obsidian:
    items:
      - OBSIDIAN
    currency:
      - '*'
    min: 10.0
    max: 1000000.0

  crying_obsidian:
    items:
      - CRYING_OBSIDIAN
    currency:
      - '*'
    min: 10.0
    max: 1000000.0

  quartz:
    items:
      - QUARTZ
    currency:
      - '*'
    min: 3.0
    max: 1000000.0

  quartz_block:
    items:
      - QUARTZ_BLOCK
    currency:
      - '*'
    min: 12.0
    max: 1000000.0
```

the default one:
```yml
version: 3
whole-number-only: false  # This option not control by enable option, always enabled
undefined: # This option not control by enable option, always enabled
  min: 0.01 # Can be zero if you want player create a free shop
  max: 999999999999999999999999999999.99 # Actually this can be up to 1.7976931348623157E308
enable: true # it was originally set to false
rules: # Rules set
  example: # Rules name, used for identifier and permission node (quickshop.price.restriction.bypass.<name>)
    #items section SUPPORT Item Expression!
    #https://quickshop-community.github.io/QuickShop-Hikari-Documents/docs/modules/item-expression
    items: # Items in the rule (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html), or the reference the item lookup table by adding @ before the name
      - STONE_SWORD
      - STONE_PICKAXE
      - STONE_AXE
      - STONE_SHOVEL
      - STONE_HOE
    currency: # Currency name, If your plugin doesn't support multi-currency (Vault API), this section won't be used
      - '*'
    min: 1.0 # Min price (double)
    max: 50.0 # Max price (double)
```
    
As I understand it, creating a STONE_SWORD shop for example on the default config should prevent creating a shop that is <1 and >50. It is not preventing the creation on my case. No, the bypass permission is not present on the player.
